### ISSUE TITLE
Request to implement RTC CRCA

### ISSUE THREAD

**Issue by oveb** [plamish/xcomfort#1]
**Fantastic work!** 
Works flawless on lighting. I have a complex xcomfort network and almost all units became available in hassio!
Are you able to integrate the new RCT CRCA?

**Comment by bengtmagne** [comment]
Brilliant work!

I have a lot of xComfort devices. 
Any way I can help? I am not a professional coder, but with some instructions, I think I can figure this out.

**Comment by plamish** [comment]
Thanks! Let me think what can be done more: adding the integration to HA core (likely would demand rebuilding async rest api calls), adding new xcomfort devices (I already added all mine), improving installation process, improvements ? Any suggestion what should be added or improved?
