### ISSUE TITLE
Wall switches not showing in HA

### ISSUE THREAD

**Issue by gulli1986** [plamish/xcomfort#11]
Hello,

Just wondering if the integration can make the wall switches available in Home Assistant so that we can use them in automations etc..?
Currently I only see my light actuators in HA, not the wall switches even though they are implemented as datapoints in MRF and in the SHC.

Is there something I am missing here?

**Comment by gulli1986** [comment]
As an example, I talked to people running [this integration](https://github.com/karloygard/xcomfortd-go) with the Communication Interface devices (Eaton xComfort CKOZ-00/14, CKOZ-00/03 USB and CCIA-0x/01 Ethernet Communication Interfaces) and they are able to use their switches in automations.

I just can't find my switches in HA using the SHC integration but I may be looking the wrong way :)

**Comment by plamish** [comment]
Switches work well, but need to defined as General function in SHC. If you have switches in the same SHC zone with lights, selected as General and still don't see them in HA please post here API log. 
To generate API log you need to have integration version >1.3. In HA go to Developer Tools->Services and call service XComfort SHC: save_status_files.  The file I need is xcomfort_devices in /config folder

**Comment by gulli1986** [comment]
@plamish thanks for your feedback.
Would you happen to know how to define the switches as a general function in MRF? I can't find a way to edit the column below with all my switches:

![a](https://user-images.githubusercontent.com/84970544/146215909-07736eb2-ae1d-423a-9b7c-6773b463e7b9.JPG)

**Comment by plamish** [comment]
You can do that from SHC web console: http://your_shc_ip_address/system/console/SystemV2#tab_devices

**Comment by gulli1986** [comment]
That's strange, I cannot change the function tap neither in MRF or in SHC...

![b](https://user-images.githubusercontent.com/84970544/146218879-a8559eba-c9df-4d4d-b93a-12a53f3e5868.JPG)

Would the switch not appear in HA if the function is empty?

**Comment by plamish** [comment]
Sorry, I think I misunderstood you. I guess we are not talking about switching actuator only about push-button switches. If that's correct, I need to admit I never tested how they are exposed by SHC.

It should be feasible to link them with virtual marker and capture status of the virtual marker in HA. 

The only issue is the integration pulls updates from SHC every few seconds. Ideally would be to get signal from xcomfort button immediately after it's pressed, but that's not possible. 

Only solution I can think of is triggering virtual marker, after a xcomfort button is pushed, for enough long time the integration can capture it's status. In other words, if you pull update every 5 seconds, after pushing button virtual marker should be ON for at least 6 seconds.

If that's option for you I can easily add virtual marker as binary sensor in HA.

**Comment by gulli1986** [comment]
You are correct, I meant push-button switches from xComfort like this one:
![a](https://user-images.githubusercontent.com/84970544/146242073-60ed23c8-bee6-47e9-a614-1f8789fa5ac0.JPG)

My thoughts were to use those switches to not only control the xComfort actuators but also Hue lights as an example by using automations.

I guess using a virtual marker would result in too much delay as you mentioned since it should be ON for at least 6 seconds.
I will try to find another way to control my Hue lights, no worries, thanks again!

**Comment by plamish** [comment]
Good news @gulli1986. After your post I started to dig and found out HA integration for Bosch SHC. xComfort SHC uses similar platform and apparently subscription based polling mechanism from Bosch SHC works well on xComfort SHC too.

It means it is feasible to rebuilt the integration API for having instant event and status messages from SHC. It likely will take me some time to code it, but I'll start working on it. In a meantime I'll try quickly code simple SHC->MQTT broker. With MQTT templates it shouldn't be complicated to get done what you plan.

Stay tuned

**Comment by gulli1986** [comment]
Wow thanks @plamish, that would be amazing! With all the wall xComfort switches I have there will be countless new automation ideas :)

**Comment by plamish** [comment]
Here you go https://github.com/plamish/xcomfort2mqtt
You can use this broker to see all events from xComfort in your HA. It shouldn't be an issue to map button with HA sensor and use it for automations.
Enjoy

**Comment by gulli1986** [comment]
Thanks @plamish, looking forward to give it a try!

**Comment by gulli1986** [comment]
Hello again @plamish.

Finally got time to test your xcomfort MQTT solution for wall switches after the Christmas holidays and wanted to send a big thank you. I can now "see" the wall switches using MQTT explorer. I still have to create HA sensors based on MQTT templates but that should be OK. This opens for a lot of automation ideas. Thank you!
