### ISSUE TITLE
where to copy files

### ISSUE THREAD

**Issue by bergemy** [plamish/xcomfort#13]
I'm a bit new to this and I'm trying to make this work but I'm not quite sure where to copy the files to. Is it to the root directory?

**Comment by plamish** [comment]
Hey bergemy, assuming you use standard config directory in your Home Assistant, you need to upload python files including translations sub-directory to /config/custom_components/xcomfort

**Comment by bergemy** [comment]
Hi plamish. Thanks for the help. I have copied the files to the right place now but unfortunately no luck. I still can't find "XComfort SHC" in integrations (Assuming you mean Configurations->Devices & Services ->Add integration). 
Not sure if I did the right thing downloading the files. I used curl in SSH & Web terminal and downloaded the files into the directories you specified and then rebooted. I have double checked the names on the directories and to me the names looks OK.

**Comment by bergemy** [comment]
Hi again. I found this in the home-assistant.log:
2022-01-04 19:24:50 ERROR (SyncWorker_0) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/xcomfort/manifest.json: Expecting value: line 7 column 1 (char 6)

**Comment by plamish** [comment]
Seems manifest.json wasn't copied properly. File Editor Add-on to HA may be very helpful in checking if all files are correctly copied

**Comment by bergemy** [comment]
Hi. 
Thanks a lot for your help. Unfortunately there was something wrong with my setup so I had to roll back to my original setup. Now it works perfectly :-)
