### ISSUE TITLE
Unable to install integration due to missing version

### ISSUE THREAD

**Issue by gulli1986** [plamish/xcomfort#2]
I get the following error message after rebooting HA:

_2021-07-20 17:07:35 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration ‘xcomfort’ does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details_

Any idea how to fix this?

**Comment by JakubJ** [comment]
> I get the following error message after rebooting HA:
> 
> _2021-07-20 17:07:35 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration ‘xcomfort’ does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details_
> 
> Any idea how to fix this?

I solved this just by manually editing my manifest.json in /config/custom_components/xcomfort/manifest.json - added a version key 1.0.0 there. After HA server restart my entioties started to work again. I'm with latest updates, core-2021.7.3.

{
  "domain": "xcomfort",
  "name": "XComfort SHC",
  "config_flow": true,
  "version":"1.0.0"
}
