### ISSUE TITLE
Warning regarding using self.async_update_ha_state()

### ISSUE THREAD

**Issue by gulli1986** [plamish/xcomfort#35]
Hello,

Using core 2023.9.2 and getting this warning this morning:

`Entity light.utelys_hybel_aktuator (<class 'custom_components.xcomfort.light.xcLight'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.`

Is it something that can be updated?

Cheers

**Comment by plamish** [comment]
Hey,
I tried to replicate the warning on my HA's, but without success. I guess it was shown only once after recent upgrade.
Anyway, I keep my HA's up-to-date and if xcomfort integration stops working, I'll fix it.
Cheers
