### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by morgansimonsen** [plamish/xcomfort#36]
HASSOS 2023.9.2
Two problems:
1. Unable to install through HACS
I can find the repo and hit Download, but it never finishes. It just keeps hanging. The files _do_ get copied to custom_components. Refreshing HACS does _not_ show the integration added, leading me to suspect an incomplete install. Have attempted cache empty and reboot.
2. Unable to configure
Since the files are seemingly in custom_components I tried adding the integration. I can find it but it just hangs on "Please wait, starting configuration wizard for xcomfort"

**Comment by plamish** [comment]
Hey morgansimonsen,
Thanks for rising. The issue should be fixed with latest release.
