### ISSUE TITLE
Error setting up entry XComfort for xcomfort

### ISSUE THREAD

**Issue by mrtobs1** [plamish/xcomfort#4]
I am very happy to see that there is a component for xcomfort, thank you very much! Unfortunately i am not getting it to work. Have always this error:

```
Logger: homeassistant.config_entries
Source: custom_components/xcomfort/xcomfortAPI.py:36
Integration: XComfort SHC (documentation, issues)
First occurred: 13:56:52 (1 occurrences)
Last logged: 13:56:52

Error setting up entry XComfort for xcomfort
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/xcomfort/__init__.py", line 27, in async_setup_entry
    await coordinator.xc.connect()
  File "/config/custom_components/xcomfort/xcomfortAPI.py", line 36, in connect
    if not self.is_connected:
AttributeError: 'xcomfortAPI' object has no attribute 'is_connected'
```

When adding the integration, what do I have to insert at URL? The local IP in my network? Username/password: I created a new user for home assistant, or do i have to use the admin? Where can i find these zone-numbers? I only have roller shutters, so do I have to fill out the heating_zones?

Thank you very much for your help.

**Comment by plamish** [comment]
I guess what happened is HA setup heating_zone radiators, but missed to find your covers. Try to remove the integration, add again, but leave all heating fields empty for zones and radiators. All empty. And for default zone start testing from 'hz_1', then try 'hz_2', etc.

**Comment by mrtobs1** [comment]
Great! Removing the integration, add again and leaving all heating fields empty solved the problem. Now all shutters and groups ar "cover". Thank you very much!
