### ISSUE TITLE
Brightness 100%

### ISSUE THREAD

**Issue by TEdvardS** [plamish/xcomfort#43]
Tanks for a great intergration.
 Works werry well exept from one issue. 
When I turn on light, it turn on with 100% brightnes.
Any idea what to do to get light to turn on with the state they had when turned off?

**Comment by plamish** [comment]
I write modified version of light component some time ago, which supports turning on lights with previous brightness. You can test it by uploading and replacing original light.py by https://github.com/plamish/xcomfort/blob/master/test/light.py in /custom_components/xcomfort folder.

**Comment by TEdvardS** [comment]
Thank you very much. Just what I was looking for.
