### ISSUE TITLE
Missing XComfort devices

### ISSUE THREAD

**Issue by jansog** [plamish/xcomfort#7]
The integration works fine for devices that are visible in HA, but not all devices turn up in HA. Any tips on how to troubleshoot this?

**Comment by plamish** [comment]
Proper formatting disappeared from my post. Check out the indentations at https://www.home-assistant.io/integrations/logger/. Second example looks like it should be

**Comment by jansog** [comment]
I am still getting Configuration invalid when validating the configuration

Integration error: custom_components.xcomfort - Integration 'custom_components.xcomfort' not found.
Integration error: default - Integration 'default' not found.
Integration error: logs - Integration 'logs' not found.

This is my configuration.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
default: warning
logs:
custom_components.xcomfort: debug

**Comment by plamish** [comment]
Keep indentations (spaces) before each line:
[no space]logger:
[space x2]default: warning
[space x2]logs:
[space x4]custom_components.xcomfort: debug

**Comment by jansog** [comment]
Finally I got the logging working.  Thanks for being patient!

I dont know what has happened but actuators configured as "general" in SHC now shows up in HA.  Looking at the logg I have a category "DoorActuator" that doesnt show up.  "BinaryDoorSensor" doesnt seem to show up in HA either.

**Comment by plamish** [comment]
I did some testing with my SHC and frankly it behaves weirdly with changing device type. I changed a device's type to Door and there was no reaction to API. Even after a reboot. Some time ago I played around with types and remember it was reflected in API. And also you can see DoorActuator and BinaryDoorSensor in your SHC. I take it as some kind of bug in SHC.
Anyway. Current version of the integration supports only "General" switch and binary sensor. My recommendation is to work with SHC to get it working. If nothing works, maybe reset to factory defaults would help.

**Comment by jansog** [comment]
Thanks for your efforts. I have the same experience with SHC behaving strange both during operation and when performing config changes. One strange thing is room controllers  (RCT) appearing differently. Hopefully one day we can swap the SHC with an open "next gen platform".  Thanks again.
